#pragma checksum "MainWindow.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "5E220A0E490E2401EEA421CF4D77971ED0B206299F01099AE626CFD987876CBA"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using MaterialDesignThemes.Wpf;
using MaterialDesignThemes.Wpf.Converters;
using MaterialDesignThemes.Wpf.Transitions;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using Tekla.Structures.Dialog;
using Tekla.Structures.Dialog.UIControls;
using TeklaStairWpfPlugin;


namespace TeklaStairWpfPlugin {
    
    
    /// <summary>
    /// MainWindow
    /// </summary>
    public partial class MainWindow : Tekla.Structures.Dialog.PluginWindowBase, System.Windows.Markup.IComponentConnector {
        
        
        #line 91 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtBox_ProfileStringers;
        
        #line default
        #line hidden
        
        
        #line 94 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Tekla.Structures.Dialog.UIControls.WpfProfileCatalog prflStringerCatalog;
        
        #line default
        #line hidden
        
        
        #line 97 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtBox_MaterialStringers;
        
        #line default
        #line hidden
        
        
        #line 99 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Tekla.Structures.Dialog.UIControls.WpfMaterialCatalog mtrlStringersCatalog;
        
        #line default
        #line hidden
        
        
        #line 132 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox textBox_ProfileStringers;
        
        #line default
        #line hidden
        
        
        #line 135 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Tekla.Structures.Dialog.UIControls.WpfProfileCatalog profileStringerCatalog;
        
        #line default
        #line hidden
        
        
        #line 138 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox textBox_MaterialStringers;
        
        #line default
        #line hidden
        
        
        #line 140 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Tekla.Structures.Dialog.UIControls.WpfMaterialCatalog materialStringersCatalog;
        
        #line default
        #line hidden
        
        
        #line 185 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtBox_ProfileStringersExt;
        
        #line default
        #line hidden
        
        
        #line 188 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Tekla.Structures.Dialog.UIControls.WpfProfileCatalog profileStringerCatalogExt;
        
        #line default
        #line hidden
        
        
        #line 191 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox textBox_MaterialStringersExt;
        
        #line default
        #line hidden
        
        
        #line 194 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Tekla.Structures.Dialog.UIControls.WpfMaterialCatalog materialStringersCatalogExt;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/TeklaStairWpfPlugin;component/mainwindow.xaml", System.UriKind.Relative);
            
            #line 1 "MainWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.txtBox_ProfileStringers = ((System.Windows.Controls.TextBox)(target));
            return;
            case 2:
            this.prflStringerCatalog = ((Tekla.Structures.Dialog.UIControls.WpfProfileCatalog)(target));
            
            #line 94 "MainWindow.xaml"
            this.prflStringerCatalog.SelectClicked += new System.EventHandler(this.prflStringerCatalog_SelectClicked);
            
            #line default
            #line hidden
            
            #line 95 "MainWindow.xaml"
            this.prflStringerCatalog.SelectionDone += new System.EventHandler(this.prflStringerCatalog_SelectionDone);
            
            #line default
            #line hidden
            return;
            case 3:
            this.txtBox_MaterialStringers = ((System.Windows.Controls.TextBox)(target));
            return;
            case 4:
            this.mtrlStringersCatalog = ((Tekla.Structures.Dialog.UIControls.WpfMaterialCatalog)(target));
            
            #line 100 "MainWindow.xaml"
            this.mtrlStringersCatalog.SelectClicked += new System.EventHandler(this.mtrlStringersCatalog_SelectClicked);
            
            #line default
            #line hidden
            
            #line 101 "MainWindow.xaml"
            this.mtrlStringersCatalog.SelectionDone += new System.EventHandler(this.mtrlStringersCatalog_SelectionDone);
            
            #line default
            #line hidden
            return;
            case 5:
            this.textBox_ProfileStringers = ((System.Windows.Controls.TextBox)(target));
            return;
            case 6:
            this.profileStringerCatalog = ((Tekla.Structures.Dialog.UIControls.WpfProfileCatalog)(target));
            
            #line 135 "MainWindow.xaml"
            this.profileStringerCatalog.SelectClicked += new System.EventHandler(this.profileStringerCatalog_SelectClicked);
            
            #line default
            #line hidden
            
            #line 136 "MainWindow.xaml"
            this.profileStringerCatalog.SelectionDone += new System.EventHandler(this.profileStringerCatalog_SelectionDone);
            
            #line default
            #line hidden
            return;
            case 7:
            this.textBox_MaterialStringers = ((System.Windows.Controls.TextBox)(target));
            return;
            case 8:
            this.materialStringersCatalog = ((Tekla.Structures.Dialog.UIControls.WpfMaterialCatalog)(target));
            
            #line 141 "MainWindow.xaml"
            this.materialStringersCatalog.SelectClicked += new System.EventHandler(this.materialStringersCatalog_SelectClicked);
            
            #line default
            #line hidden
            
            #line 142 "MainWindow.xaml"
            this.materialStringersCatalog.SelectionDone += new System.EventHandler(this.materialStringersCatalog_SelectionDone);
            
            #line default
            #line hidden
            return;
            case 9:
            this.txtBox_ProfileStringersExt = ((System.Windows.Controls.TextBox)(target));
            return;
            case 10:
            this.profileStringerCatalogExt = ((Tekla.Structures.Dialog.UIControls.WpfProfileCatalog)(target));
            
            #line 188 "MainWindow.xaml"
            this.profileStringerCatalogExt.SelectClicked += new System.EventHandler(this.profileStringerCatalogExt_SelectClicked);
            
            #line default
            #line hidden
            
            #line 189 "MainWindow.xaml"
            this.profileStringerCatalogExt.SelectionDone += new System.EventHandler(this.profileStringerCatalogExt_SelectionDone);
            
            #line default
            #line hidden
            return;
            case 11:
            this.textBox_MaterialStringersExt = ((System.Windows.Controls.TextBox)(target));
            return;
            case 12:
            this.materialStringersCatalogExt = ((Tekla.Structures.Dialog.UIControls.WpfMaterialCatalog)(target));
            
            #line 195 "MainWindow.xaml"
            this.materialStringersCatalogExt.SelectClicked += new System.EventHandler(this.materialStringersCatalogExt_SelectClicked);
            
            #line default
            #line hidden
            
            #line 196 "MainWindow.xaml"
            this.materialStringersCatalogExt.SelectionDone += new System.EventHandler(this.materialStringersCatalogExt_SelectionDone);
            
            #line default
            #line hidden
            return;
            case 13:
            
            #line 231 "MainWindow.xaml"
            ((Tekla.Structures.Dialog.UIControls.WpfOkApplyModifyGetOnOffCancel)(target)).ApplyClicked += new System.EventHandler(this.WPFOkApplyModifyGetOnOffCancel_ApplyClicked);
            
            #line default
            #line hidden
            
            #line 232 "MainWindow.xaml"
            ((Tekla.Structures.Dialog.UIControls.WpfOkApplyModifyGetOnOffCancel)(target)).CancelClicked += new System.EventHandler(this.WPFOkApplyModifyGetOnOffCancel_CancelClicked);
            
            #line default
            #line hidden
            
            #line 233 "MainWindow.xaml"
            ((Tekla.Structures.Dialog.UIControls.WpfOkApplyModifyGetOnOffCancel)(target)).GetClicked += new System.EventHandler(this.WPFOkApplyModifyGetOnOffCancel_GetClicked);
            
            #line default
            #line hidden
            
            #line 234 "MainWindow.xaml"
            ((Tekla.Structures.Dialog.UIControls.WpfOkApplyModifyGetOnOffCancel)(target)).ModifyClicked += new System.EventHandler(this.WPFOkApplyModifyGetOnOffCancel_ModifyClicked);
            
            #line default
            #line hidden
            
            #line 235 "MainWindow.xaml"
            ((Tekla.Structures.Dialog.UIControls.WpfOkApplyModifyGetOnOffCancel)(target)).OkClicked += new System.EventHandler(this.WPFOkApplyModifyGetOnOffCancel_OkClicked);
            
            #line default
            #line hidden
            
            #line 236 "MainWindow.xaml"
            ((Tekla.Structures.Dialog.UIControls.WpfOkApplyModifyGetOnOffCancel)(target)).OnOffClicked += new System.EventHandler(this.WPFOkApplyModifyGetOnOffCancel_OnOffClicked);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

